### ISSUE TITLE
Using variable into compose. It's possible

### ISSUE THREAD

**Issue by pascalandy** [general-notes/2DO#34]
Conclusion - This use a proprietary technoogie. It's not supported by docker yet.

---

http://blog.xebialabs.com/2016/04/11/beyond-docker-compose/

from

```
mysqldb:
  image: mysql:5.7
  environment:
    MYSQL_DATABASE: sample
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql
    MYSQL_ROOT_PASSWORD: supersecret
mywildfly:
  image: arungupta/wildfly-mysql-javaee7
  links:
    - mysqldb:db
  ports:
    - 8080:8080
```
to

```
mysqldb:
  image: mysql:5.7
  environment:
    MYSQL_DATABASE: {{MYSQL_DB_NAME}}
    MYSQL_USER: {{MYSQL_DB_USER}}
    MYSQL_PASSWORD: {{MYSQL_DB_PASSWORD}}
    MYSQL_ROOT_PASSWORD: {{MYSQL_DB_ROOT_PASSWORD}}
mywildfly:
  image: arungupta/wildfly-mysql-javaee7
  links:
    - mysqldb:db
  ports:
    - {{HOST_PORT}}:8080
```
